import Owner from "./owner";

type Repo = {
    id: number,
    node_id: string,
    name: string,
    full_name: string,
    private: boolean,
    owner: Owner,
    html_url: string,
    description: string | null,
    fork: boolean,
    url: string,
    forks_url: string | null,
    keys_url: string | null,
    collaborators_url: string | null,
    teams_url: string | null,
    hooks_url: string | null,
    issue_events_url: string | null,
    events_url: string | null,
    assignees_url: string | null,
    branches_url: string | null,
    tags_url: string | null,
    blobs_url: string | null,
    git_tags_url: string | null,
    git_refs_url: string | null,
    trees_url: string | null,
    statuses_url: string | null,
    languages_url: string | null,
    stargazers_url: string | null,
    contributors_url: string | null,
    subscribers_url: string | null,
    subscription_url: string | null,
    commits_url: string | null,
    git_commits_url: string | null,
    comments_url: string | null,
    issue_comment_url: string | null,
    contents_url: string | null,
    compare_url: string | null,
    merges_url: string | null,
    archive_url: string | null,
    downloads_url: string | null,
    issues_url: string | null,
    pulls_url: string | null,
    milestones_url: string | null,
    notifications_url: string | null,
    labels_url: string | null,
    releases_url: string | null,
    deployments_url: string | null,
    created_at: string | null,
    updated_at: string,
    pushed_at: string,
    git_url: string | null,
    ssh_url: string | null,
    clone_url: string | null,
    svn_url: string | null,
    homepage: string | null,
    size: number | null,
    stargazers_count: number,
    watchers_count: number | null,
    language: string | null,
    has_issues: boolean,
    has_projects: boolean,
    has_downloads: boolean,
    has_wiki: boolean,
    has_pages: boolean,
    has_discussions: boolean,
    forks_count: number | null,
    mirror_url: string | null,
    archived: boolean,
    disabled: boolean,
    open_issues_count: number | null,
    license: string | null,
    allow_forking: boolean,
    is_template: boolean,
    web_commit_signoff_required: boolean,
    topics: string[] | null,
    visibility: string | null,
    forks: number | null,
    open_issues: number | null,
    watchers: number | null,
    default_branch: string
}

export default Repo
