type User = {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string | null,
    gravatar_id: string | null,
    url: string,
    html_url: string,
    followers_url: string | null,
    following_url: string | null,
    gists_url: string | null,
    starred_url: string | null,
    subscriptions_url: string | null,
    organizations_url: string | null,
    repos_url: string | null,
    events_url: string | null,
    received_events_url: string | null,
    type: string | null,
    site_admin: boolean,
    name: string,
    company: string | null,
    blog: string | null,
    location: string | null,
    email: string | null,
    hireable: boolean,
    bio: string | null,
    twitter_username: string | null,
    public_repos: number,
    public_gists: number,
    followers: number,
    following: number,
    created_at: string,
    updated_at: string
}
export default User
